Updates for linux

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -136,7 +136,7 @@ add_line () {
 setup_gitconfig
 install_dotfiles
 
-# If we're on a Mac, let's install and setup homebrew.
+# If we're on a Mac or Linux, let's install and setup homebrew.
 if [ "$(uname -s)" == "Darwin" ]
 then
   info "installing dependencies"
@@ -151,7 +151,7 @@ then
   fi
 fi
 
-jldeenMods () {
+tdfMods () {
   info "starting jldeen mods"
   #backup old bin, if exists
   if [ -d $HOME/bin ]; then
@@ -167,7 +167,7 @@ jldeenMods () {
   fi
 }
 
-jd_Symlinks () {
+tdf_Symlinks () {
   # symlink .dotfiles bin to ~
   ln -s $HOME/.dotfiles/bin $HOME/bin && success "symlink for $HOME/bin folder created"
 
@@ -175,32 +175,39 @@ jd_Symlinks () {
   ln -s $HOME/.dotfiles/tmux $HOME/.tmux && success "symlink for $HOME/.tmux folder created"
 
   # symlink VSCode User Settings
-  if [ -d $HOME/Library/Application\ Support/Code/User ] ; then
-    echo "Making backup of current settings.json and creating symlink..."
-    echo ''
-    mv $HOME/Library/Application\ Support/Code/User/settings.json $HOME/Library/Application\ Support/Code/User/settings.old.json && success "settings.old.json created"
-    ln -s $HOME/.dotfiles/code/settings.json $HOME/Library/Application\ Support/Code/User/settings.json && success "settings.json for vs code symlink created"
+  if [ "$(uname -s)" == "Darwin" ] && [ -d $HOME/Library/Application\ Support/Code/User ] ; then 
+      echo "Making backup of current settings.json and creating symlink..."
+      echo ''
+      mv $HOME/Library/Application\ Support/Code/User/settings.json $HOME/Library/Application\ Support/Code/User/settings.old.json && success "settings.old.json created"
+      ln -s $HOME/.dotfiles/code/settings.json $HOME/Library/Application\ Support/Code/User/settings.json && success "settings.json for vs code symlink created"
+  elif [[ test "$(expr substr $(uname -s) 1 5)" = "Linux" ]] && [ -d $HOME/.vscode ] ; then 
+      echo "Making backup of current settings.json and creating symlink..."
+      echo ''
+      mv $HOME/.vscode/settings.json $HOME/.vscode/settings.old.json && success "settings.old.json created"
+      ln -s $HOME/.dotfiles/code/settings.json $HOME/.vscode/settings.json && success "settings.json for vs code symlink created"
   else
-    info "symlink for vs code settings not created"
-    echo "VS Code does not appear to be installed or has not been launched yet. Cannot create symlink for VS Code User settings..."
+      info "symlink for vs code settings not created"
+      echo "VS Code does not appear to be installed or has not been launched yet. Cannot create symlink for VS Code User settings..."
   fi
 
-  # airport symlink
-  if ! [ -f /usr/local/bin/airport ]
-    then
-      sudo ln -s /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/local/bin/airport
-      success "symlink for airport created"
-    else 
-      info "symlink for airport already exists"
+    # airport symlink
+  if test "$(uname)" = "Darwin"
+    if ! [ -f /usr/local/bin/airport ]
+      then
+        sudo ln -s /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/local/bin/airport
+        success "symlink for airport created"
+      else 
+        info "symlink for airport already exists"
     fi
+  fi
 }
 
-jdcolors () {
+tdfcolors () {
   # colorls setup
   sudo gem install colorls && success 'ls colors have been configured'
 }
 
-jdcrontab () {
+tdfcrontab () {
   #crontab additions
   add_line "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
     if [[ $? -eq 0 ]]
@@ -235,7 +242,7 @@ jdcrontab () {
   success "speedtest-cli bandwidth.json created"
 }
 
-jditermConfig () {
+tdfItermConfig () {
   # iterm2 config
   read -p "Do you currently use iTerm2 and would you like to set jldeen's custom colors? y/n " -n 1 -r
   echo ''
@@ -256,13 +263,13 @@ jditermConfig () {
   fi
 }
 
-jdFontSetup () {
+tdfFontSetup () {
   # install Source Code Pro nerd font
   cp $HOME/.dotfiles/Source\ Code\ Pro\ Nerd\ Font\ Complete.ttf /Library/Fonts
   success "Source Code Pro font copied successfully!"
 }
 
-jdconfigFix () {
+tdfConfigFix () {
   # .config permissions fix
   if [ -d "$HOME/.config" ]; then
     info "$HOME/.config doesn't exist, nothing to fix"
@@ -272,12 +279,21 @@ jdconfigFix () {
   fi
 }
 
-jldeenMods
-# jd_Symlinks
-jdcolors
-jdcrontab
-# jditermConfig
-# jdFontSetup
-# jdconfigFix
+tdfNeovimBootstrap () {
+  if [ -d "$HOME/.config/nvim" ]; then
+    echo 'Backing up existing neovim configuration.'
+    mv "$HOME/.config/nvim" "$HOME/.config/nvim.bak"
+    ln -s $HOME/.dotfiles/nvim/ $HOME/.config/nvim && success "NeoVim config backup and symlink created"
+  fi
+}
 
-success 'Badass macOS terminal installed!'
+tdfMods
+tdf_Symlinks
+tdfcolors
+tdfcrontab
+tdfItermConfig
+tdfFontSetup
+tdfConfigFix
+tdfNeovimBootstrap
+ 
+success 'Badass terminal installed!'
